apiVersion: v1
kind: PersistentVolume
metadata:
  name: mpvol1
spec:
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kvols/mpv1


  
