apiVersion: v1
kind: PersistentVolume
metadata:
  name: mpwlvol1
  labels:
    pvlabel: test1
spec:
   capacity:
     storage: 1Gi
   accessModes:
     - ReadWriteOnce
     - ReadOnlyMany
   persistentVolumeReclaimPolicy: Retain
   hostPath:
     path: /kvols/mpv1wl