apiVersion: v1
kind: PersistentVolume
metadata:
  name: mpvol3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kvols/mpvol3
