kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mppvc1
spec:
  selector:
    matchLabels:
      pvlabel: test1
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
