kind: PersistentVolume
apiVersion: v1
metadata:
  name: mpvol2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kvols/mpvol2
