global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - 192.168.50.2:8080
      - 192.168.50.3:8080
      - 192.168.50.4:8080

 - job_name: 'hbase'
   static_configs:
    - targets:
      - 192.168.50.2:7000
      - 192.168.50.3:7000
      - 192.168.50.4:7000